name: flutter_mini_sprite
description: Provides Widgets to render mini sprites into Flutter
homepage: https://github.com/bluefireteam/mini_sprite
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mini_sprite: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
