name: flame_mini_sprite
description: Library to act as a bridge betwenn Mini Sprite and Flame Engine
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.2.1
  mini_sprite: 1.0.0+1

dev_dependencies:
  flame_test: ^1.6.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
