name: flame_mini_sprite
description: Library to act as a bridge betwenn Mini Sprite and Flame Engine
version: 0.0.1+2
homepage: https://github.com/bluefireteam/mini_sprite

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ^1.14.0
  flutter:
    sdk: flutter
  mini_sprite: ^0.1.0
dev_dependencies:
  flame_test: ^1.15.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
