name: mini_treasure_quest
description: A game about a pirate hunting for treasure on dungeons

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flame: 1.2.1
  flame_behaviors: ^0.1.1
  flame_forge2d: ^0.12.1
  flame_mini_sprite: 0.0.1+2
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  mini_sprite: 0.1.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  assets:
    - google_fonts/
