name: flutter_mini_sprite_example
description: Example app for flutter_mini_sprite

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dashbook: ^0.1.10
  flutter:
    sdk: flutter
  flutter_mini_sprite: ^0.0.1
  mini_sprite: ^0.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
