name: mini_sprite_editor
description: Small, standalone application that can read and write mini sprites
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  collection: ^1.16.0
  equatable: ^2.0.3
  flame: 1.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.0.0-dev.3
  intl: ^0.17.0
  mini_sprite: 1.0.0+1
  path_provider: ^2.0.11
  replay_bloc: ^0.2.2

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
