name: mini_sprite_editor
description: Small, standalone application that can read and write mini sprites
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  bloc: ^8.0.3
  collection: ^1.16.0
  equatable: ^2.0.3
  file_selector: ^0.9.0
  flame: 1.32.0
  flame_bloc: ^1.12.15
  flame_mini_sprite: 0.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.0.0-dev.3
  image: ^4.5.4
  intl: ^0.20.2
  mini_sprite: 0.1.0
  path_provider: ^2.0.11
  replay_bloc: ^0.2.2

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
