name: mini_sprite

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/mini_sprite.yaml
      - packages/mini_sprite/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/mini_sprite.yaml
      - packages/mini_sprite/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@main

      - name: Install Dependencies
        run: melos bootstrap

      - name: Format
        run: melos exec --scope mini_sprite dart format --set-exit-if-changed lib

      - name: Analyze
        run: melos exec --scope mini_sprite dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: melos exec --scope mini_sprite flutter test --coverage

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: packages/mini_sprite/coverage/lcov.info
          min_coverage: 100
