name: mini_treasure_quest

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/mini_treasure_quest.yaml
      - packages/mini_treasure_quest/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/mini_treasure_quest.yaml
      - packages/mini_treasure_quest/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@main

      - name: Install Dependencies
        run: melos bootstrap

      - name: Format
        run: melos exec --scope mini_treasure_quest flutter format --set-exit-if-changed lib

      - name: Analyze
        run: melos exec --scope mini_treasure_quest flutter analyze --fatal-infos --fatal-warnings .
